<?php

namespace Database\Seeders;

use App\Livewire\Dashboard\Customs;
use App\Models\CustomDetail;
use App\Models\Reciept;
use App\Models\Transaction;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $t1 = Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 1,
            'district_id' => 1,
            'transaction_date' => now(),
            'category' => 'markets',
            'entity' => 'markets',
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 350,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(1), 
            // Set the created_at date for the second transaction
        ]);
        $t2 = Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'category' => 'markets',
            'entity' => 'markets',
            'total_amount' => 150,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(2),
        ]);
        $t2 = Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'category' => 'markets',
            'entity' => 'markets',
            'total_amount' => 150,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(2),
        ]);
        $t3 = Transaction::create([
            'stream_id' => 2,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 3,
            'district_id' => 3,
            'transaction_date' => now(),
            'total_amount' => 453,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'created_at' => now()->subDays(3),
        ]);
        $t4 = Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 1,
            'district_id' => 1,
            'transaction_date' => now(),
            'total_amount' => 150,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(2),
        ]);
        $t5 = Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(4),
        ]);

        CustomDetail::create([
            'transaction_id' => $t5->id,
            'type' => 'vehicle',
            'vehicleRegNumber' => '8383762739',
            'entity' => 'vehicle'
        ]);

        Reciept::create([
            'transaction_id' => $t5->id,
            'receipt_number' =>$t3->id + 100,
        ]);

        Reciept::create([
            'transaction_id' => $t1->id,
            'receipt_number' =>$t3->id + 100,
        ]);

        Reciept::create([
            'transaction_id' => $t2->id,
            'receipt_number' =>$t3->id + 100,
        ]);

        Reciept::create([
            'transaction_id' => $t3->id,
            'receipt_number' =>$t3->id + 100,
        ]);

        Reciept::create([
            'transaction_id' => $t4->id,
            'receipt_number' =>$t3->id + 100,
        ]);

        Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(5),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(4),
        ]);Transaction::create([
            'stream_id' => 2,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(3),
        ]);Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(5),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(6),
        ]);Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 3,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(6),
        ]);Transaction::create([
            'stream_id' => 2,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 1,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(6),
        ]);Transaction::create([
            'stream_id' => 2,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 3,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(7),
        ]);Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 3,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(4),
        ]);Transaction::create([
            'stream_id' => 2,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(4),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 3,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(2),
        ]);Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(3),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 3,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(2),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(8),
        ]);Transaction::create([
            'stream_id' => 2,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(9),
        ]);Transaction::create([
            'stream_id' => 2,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(10),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 1,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(12),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 1,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(12),
        ]);Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 2,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(14),
        ]);Transaction::create([
            'stream_id' => 3,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 1,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(15),
        ]);Transaction::create([
            'stream_id' => 1,
            'customer_id' => null,
            'employee_id' => null,
            'terminal_id' => 2,
            'district_id' => 3,
            'transaction_date' => now(),
            'total_amount' => 350,
            'discount_amount' => 0,
            'tax_amount' => 0,
            'net_amount' => 150,
            'payment_method' => 'cash',
            'payment_status' => 1,
            'created_at' => now()->subDays(20),
        ]);
    }
}
